#+title: Sebastian Halbigs webpage

* About me
Currently, I am a research assistant in the team of [[https://www.uni-marburg.de/en/fb12/research-groups/algeblie][Istvan Heckenberger]] at the Philipps-Universität Marburg.
Prior to that, I was a PhD student of [[https://tu-dresden.de/mn/math/geometrie/kraehmer/startseite][Ulrich Krähmer]] at the TU Dresden.

My research lives at the intersection of three areas:
 - Hopf algebras and their representation theory,
 - the theory of monoidal categories in its various flavours, and (to a lesser extend)
 - low-dimensional topology.




Preprints of articles by my coauthors and me can be found on the [[https://arxiv.org/search/?query=Halbig%2C+Sebastian&searchtype=author&abstracts=show&order=-announced_date_first&size=50][arXiv]].
Reviews and an overview of all published articles is on [[https://zbmath.org/authors/halbig.sebastian][zbMATH]].

* Publications

** Preprints
1. S. Halbig and T.Zorman. ~Pivotality, twisted centres and the anti-double of a Hopf monad~. (2022).
** Published articles
1. S. Halbig. ~Generalised Taft algebras and pairs in involution~. Commun. Algebra. (2021).
2. S. Halbig and U. Krähmer ~A Hopf algebra without a modular pair in involution~. Geom. Methods in Physics XXXVII. (2019).

** Other publications
A digital version of my PhD thesis can be found [[https://tud.qucosa.de/api/qucosa%3A80342/attachment/ATT-0/][here]].

* Talks
** 2023
** 2022
30.05.2022 /Quantum groups seminar/
"Pivotality, twisted centres and the anti-double of a Hopf monad"

15.05.2022 /PSSL Brno/
"Pivotality, twisted centres and the anti-double of a Hopf monad"

12.05.2022 /Czech academy of sciences in Prague/
"Pivotality, twisted centres and the anti-double of a Hopf monad"

12.04.2022 /Universität Hamburg/
"Pivotality, twisted centres and the anti-double of a Hopf monad"

** 2021

09.12.2021 /Czech academy of sciences in Prague/
"Exploring the Kitaev lattice model"

28.01.2021 /Promotionen und Postdocs in Darstellungstheorie (online)/
"Generalised Taft algebras and pairs in involution"

** 2020

09.11.2020 /Geometric methods seminar Dresden/
"Reconstruction of fusion categories"

20.01,2020 /RWTH Aachen/
"Generalised Taft algebras and pairs in involution"

** 2019

16.12.2019 /Friedrich–Alexander University Erlangen/
"Generalised Taft algebras and pairs in involution"

30.09.2019 /Univerité Blaise–Pascal Clermont–Ferrand/
"Generalised Taft algebras and pairs in involution"

08.07.2019 /Phillips–Universität Marburg/
"Generalised Taft algebras and pairs in involution"

** 2018

19.11.2018 /Institute of mathematics of the Polish academy of sciences/
"Generalised Taft algebras and pairs in involution"

* Teaching
** 2023
** 2022
winter term: linear algebra (teaching assisstant)

summer term: geometry for civil engineers (tutor)
** 2021
winter term: mathematics for industrial engineers (teaching assistant)

summer term: linear algebra for teachers (tutors)
** 2020
winter term: lineare Algebra (tutor)

summer term: Galois theory (teaching assistant)
** 2019
winter term: mathematics for industrial engineers (tutor)

summer term: mathematics for engineers (tutor)
** 2018
winter term: mathematics for industrial engineers (tutor)


#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="modern.css" />
#+OPTIONS: toc:nil
#+TOC_NO_HEADING: t
#+bibliography: articles.bib
#+cite_export: csl
