#+title: Sebastian Halbig

* About me
Currently, I am a research assistant in the team of [[https://www.uni-marburg.de/en/fb12/research-groups/algeblie][Istvan Heckenberger]] at the Philipps-Universität Marburg. Prior to that, I was a PhD student of [[https://tu-dresden.de/mn/math/geometrie/kraehmer/startseite][Ulrich Krähmer]] at the TU Dresden.

My research lives at the intersection of three areas:
 - Hopf algebras and their representation theory,
 - the theory of monoidal categories in its various flavours, and (to a lesser extend)
 - low-dimensional topology.

You can reach me via mail: [[mailto:Sebastian.Halbig@uni-marburg.de][Sebastian.Halbig@uni-marburg.de]]
* Publications
Preprints of articles by my coauthors and me can be found on the [[https://arxiv.org/search/?query=Halbig%2C+Sebastian&searchtype=author&abstracts=show&order=-announced_date_first&size=50][arXiv]].
Reviews and an overview of all published articles are on [[https://zbmath.org/authors/halbig.sebastian][zbMATH]].

** Preprints
1. S. Halbig and T.Zorman. ~Duality in Monoidal Categories~. (2024).
2. S. Halbig and T.Zorman. ~Diagrammatics for Comodule Monads~. (2023).
3. B. Femić and S. Halbig. ~Categorical centers and Yetter–Drinfel`d-modules as 2-categorical (bi)lax structures~. (2023).
** Published articles
1. S. Halbig and T.Zorman. ~Pivotality, twisted centres and the anti-double of a Hopf monad~. Theory Appl. Categ. (2024).
2. S. Halbig. ~Generalised Taft algebras and pairs in involution~. Commun. Algebra. (2021).
3. S. Halbig and U. Krähmer ~A Hopf algebra without a modular pair in involution~. Geom. Methods in Physics XXXVII. (2019).
** Other publications
A digital version of my PhD thesis can be found [[https://tud.qucosa.de/api/qucosa%3A80342/attachment/ATT-0/][here]].

* Conferences, talks and research visits
** 2024
+ 29.04. - 03.05.2024 Research visit in /Bonn/
+ 26.02. - 27.02.2024 Research visit in /Dresden/
+ 19.02.2024 - 23.05.2024 Research visit in /Brno/
  + 21.02.2024 Talk in the /Brno Algebra seminar:/  "Dualities in monoidal functor categories"
+ 28.01. - 02.02.2024 /Oberwolfach Mini-workshop:/ "Bridging Number Theory and Nichols Algebras via Deformations"
  + 02.02.2024 Talk: "Dualities in abelian monoidal functor categories"
** 2023
+ 23.11. - 26.11.2023 /Factorisation homology seminar/ in Dresden
  + Talks on the 24.11 and the 25.11
+ 20.10. - 22.10.2023 /Factorisation homology seminar/ in Bonn
+ 04.09. - 06.09.2023 /Hopf days/ in Brussels
  + 04.09 Talk "Duality in monoidal categories"
+ 14.07. - 15.07.2023 Seminar on /Mackey functors/ co-organised with T. Zorman
+ 02.07. - 08.07.2023 /Category Theory 2023/ in Louvain-la-Neuve
+ 22.05. - 26.05.2023 Workshop /Hopf Algebras and Tensor Categories/ in Marburg
  + 23.05 Talk " Pairs in involution – From Hopf algebras to monoidal categories and back"
** 2022
+ 08.12. - 11.12.2022 Seminar on /Operads/ in Bonn
+ 05.12. - 08.12.2022 Research visit in /Erlangen/
+ 30.05.2022 /Quantum groups seminar/
  "Pivotality, twisted centres and the anti-double of a Hopf monad"
+ 15.05.2022 /PSSL Brno/
  "Pivotality, twisted centres and the anti-double of a Hopf monad"
+ 12.05.2022 /Czech academy of sciences in Prague/
  "Pivotality, twisted centres and the anti-double of a Hopf monad"
+ 12.04.2022 /Universität Hamburg/
  "Pivotality, twisted centres and the anti-double of a Hopf monad"
** 2021
+ 09.12.2021 /Czech academy of sciences in Prague/
  "Exploring the Kitaev lattice model"
+ 28.01.2021 /Promotionen und Postdocs in Darstellungstheorie (online)/
  "Generalised Taft algebras and pairs in involution"
** 2020
+ 09.11.2020 /Geometric methods seminar Dresden/
  "Reconstruction of fusion categories"
+ 20.01.2020 /RWTH Aachen/
  "Generalised Taft algebras and pairs in involution"
** 2019
+ 16.12.2019 /Friedrich–Alexander University Erlangen/
  "Generalised Taft algebras and pairs in involution"
+ 30.09.2019 /Univerité Blaise–Pascal Clermont–Ferrand/
  "Generalised Taft algebras and pairs in involution"
+ 08.07.2019 /Phillips–Universität Marburg/
  "Generalised Taft algebras and pairs in involution"
** 2018
+ 19.11.2018 /Institute of mathematics of the Polish academy of sciences/
  "Generalised Taft algebras and pairs in involution"
* Teaching
** 2024
summer term: Representation theory of finite groups (lecturer)
** 2023
winter term: Basic concepts of linear algebra (teaching assistant),
             Algebra (teaching assitant)

summer term: Representation theory of algebras (teaching assistant),
             linear algebra II (teaching assistang)
** 2022
winter term: linear algebra (teaching assisstant)

summer term: geometry for civil engineers (tutor)
** 2021
winter term: mathematics for industrial engineers (teaching assistant)

summer term: linear algebra for teachers (tutors)
** 2020
winter term: linear algebra (tutor)

summer term: Galois theory (teaching assistant)
** 2019
winter term: mathematics for industrial engineers (tutor)

summer term: mathematics for engineers (tutor)
** 2018
winter term: mathematics for industrial engineers (tutor)


#+OPTIONS: toc:nil
#+TOC_NO_HEADING: t
